feat: add expression evaluation
grokking-vietnam/grox pull request #101
Opened 2022-03-26 08:55 UTC by akizminet

Thêm implement của Chapter 7.

Todo:

- [ ] def evaluate
- [ ] RuntimeError

2022-04-30 03:18 UTC, lenguyenthanh requested changes

2022-04-30 03:21 UTC, lenguyenthanh commented on compiler/src/main/scala/grox/Interpreter.scala
> +      case Expr.Divide(l, r)   => (evaluate(l), evaluate(r)) match
thêm `DevideByZero` error

2022-04-30 03:31 UTC, lenguyenthanh commented
Để code đỡ rối em có thể refactor như sau:

```scala
  type EvaluationResult = Either[RuntimeError, Literal]
  type Evaluate = (LiteralType, LiteralType) => EvaluationResult

  def add(left: LiteralType, right: LiteralType): EvaluationResult =
    (left, right) match
      case (l: Double, r: Double) => Right(l + r)
      case (l: String, r: String) => Right(l ++ r)
      case _                      => Left(EvaluationError.Unexpected)


  def evaluate(eval: Evaluate)(left: EvaluationResult, right: EvaluationResult): EvaluationResult =
    (left, right).mapN(eval).flatten

  // trong evalute(expr) em có thể dùng như sau
  case Expr.Multiply(l, r) => evaluate(add)(evaluate(l), evaluate(r))
```

2022-05-07 03:55 UTC, akizminet commented on compiler/src/main/scala/grox/Interpreter.scala
> +  def evaluate(expr: Expr): Either[RuntimeError, Any] =
Em thấy có map sang Java Object nên để Any. Có vẻ như là do Java không có union type.

2022-05-08 06:29 UTC, lenguyenthanh commented on compiler/src/main/scala/grox/Interpreter.scala
> +  def evaluate(expr: Expr): Either[RuntimeError, Any] =
java sida lắm =))

2022-05-14 08:45 UTC, lenguyenthanh commented on compiler/src/main/scala/grox/Interpreter.scala
> +          case null       => null
Cái này cũng nên return Right(null) chứ nhỉ?

thành ra cái case này có thể sửa thành `case Expr.Literal(value)` => Right(value)` luôn.

2022-05-14 08:45 UTC, lenguyenthanh commented on compiler/src/main/scala/grox/Interpreter.scala
> +          case null       => null
Cái này cũng nên return Right(null) chứ nhỉ?

thành ra cái case này có thể sửa thành `case Expr.Literal(value)` => Right(value)` luôn.

2022-05-20 13:14 UTC, akizminet commented on compiler/src/main/scala/grox/Interpreter.scala
> +          case null       => null
Em mới xem lại, trong sách có kiểu nil riêng còn literal của mình đã có sẵn Null nên sẽ return value luôn.

2022-05-20 13:34 UTC, akizminet commented on compiler/src/main/scala/grox/Interpreter.scala
> +          case null       => null
Em mới xem lại, trong sách có kiểu nil riêng còn literal của mình đã có sẵn Null nên sẽ return value luôn.

2022-05-20 15:59 UTC, lenguyenthanh approved these changes

2022-05-20 16:11 UTC, merged