add assignment syntax
grokking-vietnam/grox pull request #119
Opened 2022-04-16 04:44 UTC by anhlt

- [ ] Add assignment syntax
- [ ] Unit tests

2022-06-21 12:43 UTC, lenguyenthanh requested changes

2022-06-21 18:43 UTC, lenguyenthanh commented on compiler/shared/src/test/scala/grox/ParserTest.scala
> +  test("assignments: expect assignment") {
đây là test var declaration chứ nhỉ?

2022-06-21 18:43 UTC, lenguyenthanh commented on compiler/shared/src/main/scala/grox/Parser.scala
> +  ): ExprParser[A] = or(tokens).flatMap((expr: Expr, restTokens: List[Token[A]]) =>
sao lại có `or(tokens)` ở đây vậy?

2022-06-25 14:16 UTC, anhlt commented on compiler/shared/src/main/scala/grox/Parser.scala
> +  def or[A]: List[Token[A]] => ExprParser[A] = binary(orOp, and)
or và and đã nằm trong assignmentrồi anh .

2022-06-25 14:33 UTC, anhlt commented on compiler/shared/src/main/scala/grox/Parser.scala
> +  ): ExprParser[A] = or(tokens).flatMap((expr: Expr, restTokens: List[Token[A]]) =>
```
assignment     → IDENTIFIER "=" assignment
               | logic_or ;
logic_or       → logic_and ( "or" logic_and )* ;
logic_and      → equality ( "and" equality )* ;


```

Nhưng or có thể là IDENTIFER hoặc Không phải IDENTIFER

Nếu như kết quả ở đây là IDENTIFER và kí tự tiếp theo là EQUAL thì sẽ tiếp tục gọi làm assignment
Nếu không thì sẽ trả về là một expression khác

2022-06-25 15:05 UTC, lenguyenthanh commented on compiler/shared/src/main/scala/grox/Parser.scala
> +  def or[A]: List[Token[A]] => ExprParser[A] = binary(orOp, and)
ý anh là cho cái `[ExprGen](https://github.com/grokking-vietnam/grox/blob/main/compiler/shared/src/test/scala/grox/ExprGen.scala)`

2022-06-25 15:16 UTC, lenguyenthanh commented on compiler/shared/src/main/scala/grox/Parser.scala
> +  def or[A]: List[Token[A]] => ExprParser[A] = binary(orOp, and)
https://github.com/grokking-vietnam/grox/issues/165

2022-06-25 15:18 UTC, lenguyenthanh commented on compiler/shared/src/main/scala/grox/Parser.scala
> +  ): ExprParser[A] = or(tokens).flatMap((expr: Expr, restTokens: List[Token[A]]) =>
à ok, anh ko để ý đoạn đó 👍

2022-06-25 15:49 UTC, lenguyenthanh approved these changes

2022-06-25 15:52 UTC, anhlt commented on compiler/shared/src/main/scala/grox/Parser.scala
> +      case Identifier(name, tag: A) :: rest => Right(Expr.Variable[A](Identifier(name, tag)), rest)
Somehow cannot compile using this way

2022-06-25 15:56 UTC, merged