Add property test for expr evaluation
grokking-vietnam/grox pull request #153
Opened 2022-06-11 10:00 UTC by hungcaox

fix #129

2022-06-11 10:43 UTC, lenguyenthanh requested changes

2022-06-11 10:43 UTC, lenguyenthanh commented on compiler/shared/src/test/scala/grox/ParserTest.scala
> +    Prop.forAll(logicalGen) { expr =>
Đoạn này chắc nên tách làm 2 property cho rõ ràng nhỉ?

2022-06-25 09:56 UTC, hungcaox commented on compiler/shared/src/test/scala/grox/ParserTest.scala
> +    Prop.forAll(logicalGen) { expr =>
Done.

2022-06-25 10:01 UTC, lenguyenthanh approved these changes

2022-06-25 10:02 UTC, merged