feat: add evaluate cli
grokking-vietnam/grox pull request #164
Opened 2022-06-24 14:24 UTC by akizminet

Resolve #130

2022-06-24 17:36 UTC, lenguyenthanh requested changes

2022-06-24 17:36 UTC, lenguyenthanh commented on cli/shared/src/main/scala/grox/cli/CLI.scala
> +    val evaluate: Opts[Command] =
Em cần 1 testcase bên `CLITest.scala`

2022-06-25 06:29 UTC, lenguyenthanh approved these changes

2022-07-07 08:50 UTC, lenguyenthanh commented
Cái này merge đượ rồi @akizminet

2022-07-07 08:51 UTC, merged

2022-07-07 08:52 UTC, lenguyenthanh requested changes

2022-07-07 08:52 UTC, lenguyenthanh commented on web/project/build.properties
> +sbt.version=1.6.2
À mà file này thì không cần thiết, có thể xoá.

2022-07-07 08:57 UTC, lenguyenthanh commented on web/project/build.properties
> +sbt.version=1.6.2
haha, merge nhanh quá, để anh tạo PR khác để xoá cái file này.

2022-07-07 08:58 UTC, akizminet commented on web/project/build.properties
> +sbt.version=1.6.2
Haha, dà anh, ngay lúc em đang online

2022-07-07 09:00 UTC, lenguyenthanh commented on web/project/build.properties
> +sbt.version=1.6.2
resolved by #179