Integrate Web Playground with homepage
grokking-vietnam/grox pull request #192
Opened 2022-07-16 07:49 UTC by akizminet

Resolve #147

2022-07-16 08:08 UTC, akizminet commented
Demo:

[Demo](https://user-images.githubusercontent.com/52618539/179346387-8a9c4755-989c-4d3b-a0fd-05d9cda919d6.webm)

2022-07-17 09:27 UTC, lenguyenthanh requested changes

2022-07-17 09:27 UTC, lenguyenthanh commented on .github/workflows/doc.yml
> +        run: sbt 'docs/mdoc;web/fastOptJS'
Dùng fullOpsJs luôn, fastOpsJs là để cho testing thôi.

2022-07-17 09:27 UTC, lenguyenthanh commented on web/project/build.properties
> +sbt.version=1.6.2
file không cần thiết.

2022-07-17 09:27 UTC, lenguyenthanh commented on website/src/pages/_playground.js
> +} from '../../../web/target/scala-3.1.3/web-fastopt.js'
có cách nào hardcode cái link này không nhỉ? Bây giờ cứ mỗi lần update scala thì mình phải update cái link này.

2022-07-18 01:45 UTC, akizminet commented on .github/workflows/doc.yml
> +        run: sbt 'docs/mdoc;web/fastOptJS'
https://github.com/scala-js/scala-js/blob/main/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPlugin.scala
Em thay bằng fullLinkJS

2022-07-18 01:45 UTC, akizminet commented on web/project/build.properties
> +sbt.version=1.6.2
Đã remove

2022-07-18 01:45 UTC, akizminet commented on website/src/pages/_playground.js
> +} from '../../../web/target/scala-3.1.3/web-fastopt.js'
Đã hardcode

2022-07-18 07:53 UTC, lenguyenthanh approved these changes
LGTM

2022-07-18 10:02 UTC, merged