err-friendly
grokking-vietnam/grox pull request #257
Opened 2023-01-08 08:55 UTC by nvduc91

After check codebase, we already have:
<img width="704" alt="ảnh" src="https://user-images.githubusercontent.com/12379860/211187941-1c352592-c93d-468c-8549-9d931649cc81.png">
and
<img width="888" alt="ảnh" src="https://user-images.githubusercontent.com/12379860/211187976-114c12ec-9699-48ad-91b0-d54907691f0a.png">

I beleave these objects enough when compile and return err detailed. PLease correct me if im wrong.
Then i did add 2 test suite for making skeleton for the rest of it. Please help to consult me for it, i comment on code.

2023-01-08 08:58 UTC, nvduc91 reviewed
@lenguyenthanh cho em tư vấn với

2023-01-08 08:58 UTC, nvduc91 commented on web/src/test/scala/grox/PlaygroundTests.scala
> +class PlaygroundTests extends munit.FunSuite:
I did use:
<img width="938" alt="ảnh" src="https://user-images.githubusercontent.com/12379860/211188074-81692f2b-a336-48fd-8252-bea6a1ae38bb.png">
 but no test to run

2023-01-08 08:58 UTC, nvduc91 commented on compiler/shared/src/test/scala/grox/ExecutorTest.scala
> +  var testee: Resource[IO, Executor[IO]] = Executor.module[IO]
Im not sure is a good way to create an instance of Executor but the idea is make it then test parse/scan with input as String. I need it to finish the rest of test suites not commit yet.
please help me to correct it

2023-01-08 10:55 UTC, lenguyenthanh requested changes

2023-01-08 10:55 UTC, lenguyenthanh commented on compiler/shared/src/test/scala/grox/ExecutorTest.scala
> +    val input = "print(\"Hello world\")"
Em nên dùng multiline string, đỡ phải escape: """

2023-01-08 10:55 UTC, lenguyenthanh commented on compiler/shared/src/test/scala/grox/ExecutorTest.scala
> +  var testee: Resource[IO, Executor[IO]] = Executor.module[IO]
looks good, except, var => val. We prefer immutable data.

2023-01-08 10:55 UTC, lenguyenthanh commented on web/src/test/scala/grox/PlaygroundTests.scala
> +class PlaygroundTests extends munit.FunSuite:
Trong PR này, em tập trung vào phần error messages, với Executor tests thôi nhé. Playground này để sau.

2023-01-08 10:55 UTC, lenguyenthanh commented on compiler/shared/src/test/scala/grox/ExecutorTest.scala
> +class ExecutorTest extends munit.FunSuite:
Vì mấy cái test này sẽ có IO, em nên dùng: CatsEffectSuite như ở đây: https://github.com/grokking-vietnam/grox/blob/fb/err-friendly/compiler/shared/src/test/scala/grox/EnvTest.scala

2023-01-08 10:55 UTC, lenguyenthanh commented on compiler/shared/src/test/scala/grox/ExecutorTest.scala
> +    val scan: Resource[IO, IO[List[Token[Span]]]] = testee.map(exe => exe.scan(input))
Với CatsEffectSuite: em có thể viết lại toàn bộ test như sau:
```
    testee.use(exe => exe.scan(input)).map { result =>
      assertEquals(result, List(Print(Span(Location(0,0,0),Location(0,5,5))), LeftParen(Span(Location(0,5,5),Location(0,6,6))), Str("Hello world",Span(Location(0,6,6),Location(0,19,19))), RightParen(Span(Location(0,19,19),Location(0,20,20)))))
    }
```

Chú ý, anh sử dụng `use` from [Resources](https://typelevel.org/cats-effect/docs/std/resource)

2023-02-06 11:07 UTC, lenguyenthanh commented on compiler/shared/src/test/scala/grox/StmtParserTest.scala
> +    parseStmt(tokensMissingRightParent) match
Lỗi ở đây: https://github.com/grokking-vietnam/grox/blob/918d208bc277ccee568cbc6cf843279fc69726d4/compiler/shared/src/main/scala/grox/Parser.scala#L64

Hiện tại mình bỏ qua error ở đây. Chỉ return List[Stmt].
Chắc ở đây nếu errors từ _parserStmt mà nonEmpty thì mình nên return Left.

2023-02-07 06:37 UTC, nvduc91 commented on compiler/shared/src/test/scala/grox/StmtParserTest.scala
> +    parseStmt(tokensMissingRightParent) match
để em thử xem

2024-05-30 00:26 UTC, closed without merging